### PR TITLE
Initial implementation of VGG CNN S caffemodel in theano

### PR DESCRIPTION
**Pull request by erfannoury**
This implementation is based on the GoogLeNet caffemodel implementation in sklearn-theano.
Output comparison with pycaffe still remains, though judging by the classifier output, there still problems are seemingly remaining unresolved.

### CODE REVIEW

**Comment by kastnerkyle** [comment]
I will try to take a look at this soon (deadlines...). Was there anything special you had to do in _parse_caffe_model that was different than the one in caffemodel.py ? If not it would be good to use that one, or figure out how to merge the two somehow.

**Comment by erfannoury** [comment]
Thank you.
Yes, I added an statement that adds layer descriptor for the first layer in the network (`data` layer) to the list of layers ([caffemodel.py L166-171](https://github.com/erfannoury/sklearn-theano/blob/vggcnns/sklearn_theano/models/vgg_cnn_s/caffemodel.py#L166:L171)).
I was thinking about merging them, but I couldn't find a better solution. Though codes are almost the same, some specific changes in the VGG CNN S version of the codes makes merging them non-trivial.

**Comment by kastnerkyle** [comment]
Sorry for the delay, I have been quite busy (as has Michael). I am hoping to take a closer look at this during the PyCon sprint next week

**Comment by erfannoury** [comment]
Hi
Oh it's ok. 
It would be great if you could take a look.
I will also try to work on it again, so that I can get sure about the implementation and maybe do some refactoring.
Thank you

**Comment by erfannoury** [comment]
The other day I was working on this issue, and I find out that fully connected layers cause the problem. I can now successfully extract network data up to `pool5` layer, in both VGG CNN S and VGG CNN 16 layer models. Should see why `fc` layers are causing the problem.

**Comment by kastnerkyle** [comment]
Superceded by #86 which uses parts of this, though we may want to reference this in a new PR for implementing the object classes and VGG 16. Thanks @erfannoury

**Pull request closed without merging**
