### PR TITLE
Added vgg caffemodel support, though no object for real use just yet

### PR DESCRIPTION
**Pull request by kastnerkyle**
Opened PR for balanced VGG (from texture classification) and VGG

@eickenberg you probably don't have time to review right now, but this incorporates changes from both @yaoli and @erfannoury . Can either of you have a look over and see if anything is amiss? If no I might merge soon - there isn't a lot of public API added, though I did have to change the output of ```parse_caffe_model``` to return params - which is a better thing in the long run IMO.

Example script I used to validate it was working for balanced vgg

```          
from sklearn_theano.feature_extraction.caffe.balanced_vgg import _get_fprop      
from sklearn_theano.datasets import load_sample_image                            
im = load_sample_image('sloth.jpg')                                              
f = _get_fprop()                                                                 
r = f(im[None].transpose(0, 3, 1, 2))   
```

### CODE REVIEW

**Comment by eickenberg** [comment]
awesome! Thanks for taking care of this! Will be able to take a look on Monday.

**Comment by erfannoury** [comment]
Thank you @kastnerkyle . This is great! I will be testing this out today.
An early inspection shows that only the VGG-19 model is used; maybe an optional argument could be added to select other VGG models, too. They all have the same architecture and they only differ in the number of layers. I have tested all of the VGG model using my PR code, so they should be working without problem with this code, too.

**Comment by kastnerkyle** [comment]
I am hoping to add the other models later, along with objects which use
them. Do you see anything I might have done that would make this annoying?
I *think* it should be easy

**Comment by kastnerkyle** [comment]
Would follow a similar format as the Overfeat objects

**Comment by erfannoury** [comment]
I tested the vgg model, works without a problem; though I can't test the correctness of output values since I don't have Caffe installed. It feels faster than back then.

Now that the core implementation seems to be working, objects like those created for Overfeat can be created easily. However, how are you going to handle the mean image or value for each network? They are not addressed right now. 

@kastnerkyle what do you mean by "making this annoying"?

**Comment by kastnerkyle** [comment]
merging.... we can clean this up later. By making this annoying I mostly mean that I haven't done anything that will *obviously* cause us problems down the road. Looking at it (1 month later) I think it is ok

**Comment by erfannoury** [comment]
Great and thank you :)

**Pull request merged**
