### PR TITLE
Added externals files and changed caffe imports

### PR DESCRIPTION
**Pull request by kastnerkyle**
With these changes, all the necessities are there without installing python-protobuf. Model file is downloaded from our Dropbox repo, and ```caffe_pb2.py``` is local to the model only.

The only necessary changes were to make the python-protobuf code relative imports. I don't know how this will work long term if we have to update the protobuf code. Especially if caffe switches to protobuf 3.0 , but we can cross that bridge when we get to it.

There is still a step pickling a list of dictionaries - don't know if it is strictly necessary but figured I would leave these changes for another commit. With this it should be possible to do VGGNet the same way, modulo the uploading of the model file to the public github which I or @eickenberg can do at any point

cc @eickenberg @erfannoury

### CODE REVIEW

**Comment by eickenberg** [comment]
I am not entirely sure I understand the relative import thing.

Why do we need to ship all of python-protobuf? I thought we were only going to ship caffe_pb2.py?

I guess I misunderstood. So caffe_pb2.py is not standalone and depends on python-protobuf? And python-protobuf is difficult to install/volatile?

**Comment by erfannoury** [comment]
python-protobuf  isn't a strict requirement. We can go away without including its code in the repository. Since installing python-protobuf is easy. But `caffe_pb2.py` has to be included in the code; thus removing the dependency on protobuf compiler.

**Comment by kastnerkyle** [comment]
Protobuf files were included because caffe_pb2.py file I got with latest
python protobuf was broken - had to use exact matching version that was
used to generate pb2 file. It seems they are moving fast and breaking
backwards compat.

If we are including the pb2 file I think we need to have a controlled
version of protobuf so that we guarantee all our pb2 files work with
included ```externals/``` version.  Otherwise we need to test against
multiple protobuf versions to ensure that changes in protobuf don't make
pb2 files incompatible. Or require an exact version which may or may not be
the one that is pip installed by default.

Also means we need to make protobuf a hard dependency - having a curated
version in ```externals/``` takes care of dependency problem and version
problem at the same time.

**Comment by kastnerkyle** [comment]
If it becomes annoying to maintain we can remove the dependency later but
this way the whole protobuf/pb2 thing becomes invisible to the user. And
hopefully easier for us to add new pb2 files by only checking against 1
canonical version.

**Comment by kastnerkyle** [comment]
So to be clear in response to @eickenberg:
```
Why do we need to ship all of python-protobuf? I thought we were only going to ship caffe_pb2.py? So caffe_pb2.py is not standalone and depends on python-protobuf?
```

Yes, caffe_pb2.py depends on python-protobuf 

```
And python-protobuf is difficult to install/volatile?
```

It is not difficult to install, but I have already run into issues with wrong versions of python-protobuf not working with files compiled with protoc (which is why I got you to email me the one you used!). This means that for new models to be added we would need to verify they work with a particular version of python-protobuf. If we have the version in ```externals/```, then it becomes easy to verify that things work with that version, and we avoid needing to pip install a particular version of python-protobuf.

**Comment by eickenberg** [comment]
OK, that makes sense. We will have to watch out for incompatibilities accumulating between the now frozen externals/protobuf and the one in the wild, but at least that way our models will run whatever happens. And that is good for users who just want to use a deep net with python.

I am having difficulties finding file changes in the diff that are not the adding of protobuf, in order to review any code additions. Are there any?

**Comment by kastnerkyle** [comment]
Only changes are in caffemodel.py - basically just removed stuff that
looked for proto file and changed paths to download from Dropbox

**Comment by eickenberg** [comment]
OK, if googlenet transformer/classifier test passes, feel free to merge,
I'm on the phone right now.

**Comment by kastnerkyle** [comment]
They pass on a brand new repo. Merging!

**Pull request merged**
